### ISSUE TITLE
brainstorm auditory link is broken

### ISSUE THREAD

**Issue by sappelhoff** [INCF/BIDS-examples#111]
`You can find the full version of brainstorm_sample_auditory here.`

The link would lead to: https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory

That's broken.

Perhaps we can link to: https://neuroimage.usc.edu/brainstorm/Tutorials/Auditory

And say something like `The brainstorm_sample_auditory is available from this webpage ...`

**Comment by jasmainak** [comment]
It's not broken. You just need to create an account ...

**Comment by sappelhoff** [comment]
I get `File not found`. What do you mean by account? Just any ownCloud account? Unfortunately that is not suggested as a solution on the site of the link. 

![image](https://user-images.githubusercontent.com/9084751/44059186-ce229856-9f50-11e8-878a-3600c06b74c9.png)

**Comment by jasmainak** [comment]
I think @guiomar can help. And yeah agree the site should be more explicit

**Comment by guiomar** [comment]
Thanks @sappelhoff , where did you get this link from?

The data could be found at: https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory
Or in MEG-BIDS format at OpenNeuro: https://openneuro.org/datasets/ds000246

Cheers!

**Comment by sappelhoff** [comment]
Hi @guiomar, I saw your post in MNE-BIDS and just corrected the link. It should now point to the OpenNeuro data.

**Comment by guiomar** [comment]
Thanks a lot!! :)
