### ISSUE TITLE
The participants.tsv in ds008 doesn't have sub-08 listed.

### ISSUE THREAD

**Issue by ellisdg** [INCF/BIDS-examples#14]
Is [this](https://github.com/INCF/BIDS-examples/blob/master/ds008/participants.tsv#L9) an error or is it allowed to not list all of the subjects in the participants.tsv file?

**Comment by chrisfilo** [comment]
It is an error - thanks for reporting! I believe the validator should fix those now. @suyashdb - could you fix this?

**Comment by suyashdb** [comment]
@ellisdg Thank you for pointing it out. Will correct this in new revision.
