### ISSUE TITLE
The download links in the README do not work

### ISSUE THREAD

**Issue by chrisfilo** [INCF/BIDS-examples#16]

**Comment by robertoostenveld** [comment]
You can find the full version of mne_sample_data [here](https://drive.google.com/drive/folders/0B_sb8NJ9KsLUQ3BMS0dxZW5nSHM).

You can find the full version of brainstorm_sample_auditory [here](https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory).

I will add these links to the README in the bep008_meg branch.

**Comment by choldgraf** [comment]
this can be closed, no?

**Comment by sappelhoff** [comment]
@robertoostenveld  this can be closed as well.
