### ISSUE TITLE
entire filenames should displayed

### ISSUE THREAD

**Issue by jbwexler** [INCF/BIDS-examples#19]
As with most github repos, long filenames are cutoff in order to make space for the other two columns (most recent commit, and date). However, given that one of the main purposes of this repo is to display filenames (commit history is not so important to most viewers), it would be nice to display the entire filenames. I have no idea whether this is possible

**Comment by robertoostenveld** [comment]
I would not know how to do this either. I hope people are any enough to git clone the example to the local computer and use the file browser and editor to explore them locally.
