### ISSUE TITLE
review and correct the MEG BIDS examples 

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#25]
there are now three MEG example datasets in the bep008_meg branch: ds000117, brainstorm_sample_auditory and mne_sample_data.

 Please clone INCF/BIDS-examples, switch to the bep008_meg branch, make a new branch based on that and send pull requests (against bep_008_meg, not against master) for any changes that you would like to see implemented.

**Comment by robertoostenveld** [comment]
@brainstorm @guiomar-niso @agramfort @martcous @ebock @sbaillet @schoffelen @cpernet @jbwexler

Could you check the MEG BIDS examples?

**Comment by agramfort** [comment]
MNE example needs work to be up to date.

@jasmainak will have look later in Aug when he is in Stanford.

I won't have much time before.

**Comment by robertoostenveld** [comment]
for reference, see also https://github.com/INCF/bids-validator/pull/301

**Comment by ebock** [comment]
I have the updated MEG BIDS examples here: https://box.bic.mni.mcgill.ca/apps/files/?dir=/OMEGA%20(2)/Contributions%20(in%20BIDS%20format)&fileid=49426
They can be included in the BIDS examples - they just need to be validated (when its ready).

**Comment by jasmainak** [comment]
@ebock is it possible to make this dataset accessible by direct link?

**Comment by ebock** [comment]
Try these:
https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory
https://box.bic.mni.mcgill.ca/s/sample_BIDS_omega

**Comment by jasmainak** [comment]
@ebock here are some errors I got on `sample_bids_auditory`:

```sh
	1: Participants and phenotype .tsv files must have a 'participant_id' column. (code: 48 - PARTICIPANT_ID_COLUMN)
		./participants.tsv
			@ line: 1
			Evidence: participant_id,age,sex,dominant_hand

	2: JSON file is not formatted according the the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .AnatomicalMRICoordinateUnits should NOT be shorter than 1 characters
		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .EEGCoordinateUnits should NOT be shorter than 1 characters
		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .LandmarkCoordinates should be string
		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .EEGCoordinateSystem should NOT be shorter than 1 characters
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .PowerLineFrequency should be number
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .DigitizedHeadPoints should be string
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .DigitizedLandmarks should be string
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .MaxMovement should be number
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .CoilFrequency should be number
		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .ContinuousHeadLocalization should be string
		... and 12 more files having this issue (Use --verbose to see them all).
```

**Comment by guiomar** [comment]
Thanks @jasmainak !

I've fixed (1) so it's not comma separated but tabular.

Regarding (2):

                 ./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .LandmarkCoordinates should be string

LandmarkCoordinates shouldn't be just a string according to the specs:
	"LandmarkCoordinates": {
		"NAS": [9.76823213,-0.11917776,-1.87417223],
		"LPA": [-0.29274026,6.88415084,0.70120923],
		"RPA": [-0.99183277,-6.70128616,0.08443862]
	},

		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .AnatomicalMRICoordinateUnits should NOT be shorter than 1 characters

Ok, we'll check freesurfer coordinate units

		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .EEGCoordinateUnits should NOT be shorter than 1 characters

EEGCoordinateUnits it's optional, in our case we don't have EEG

		./sub-0001/meg/sub-0001_task-AEF_run-01_fid.json
			Evidence: .EEGCoordinateSystem should NOT be shorter than 1 characters

EEGCoordinateSystem it's optional, in our case we don't have EEG

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .CoilFrequency should be number

This is optional

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .MaxMovement should be number

This is optional

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .DigitizedLandmarks should be boolean

Changed!

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .DigitizedHeadPoints should be boolean

Changed!

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .PowerLineFrequency should be number

Changed!

		./sub-0001/meg/sub-0001_task-AEF_run-01_meg.json
			Evidence: .ContinuousHeadLocalization should be boolean
Changed!


Thanks a lot!

**Comment by jasmainak** [comment]
@guiomar are you sure these have been fixed because I still see the comma-separated participants.tsv file here: https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory.

I also get these errors:

```sh
	3: Subject label in the filename doesn't match with the path of the file. File seems to be saved in incorrect subject directory. (code: 64 - SUBJECT_LABEL_IN_FILENAME_DOESNOT_MATCH_DIRECTORY)
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_channel.tsv
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_channel.tsv is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.acq
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.acq is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.eeg
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.eeg is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.hc
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.hc is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.hist
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.hist is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.infods
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.infods is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.infods.bak
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.infods.bak is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.meg4
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.meg4 is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.newds
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.newds is saved in incorrect subject directory as per sub-id in filename.
		./sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.res4
			Evidence: File: /sub-emptyroom/meg/sub-0001_task-noise_run-01_meg.ds/sub-0001_task-noise_run-01_meg.res4 is saved in incorrect subject directory as per sub-id in filename.
		... and 2 more files having this issue (Use --verbose to see them all).
```

**Comment by guiomar** [comment]
Sorry, I did it in my local version

**Comment by ebock** [comment]
@guiomar @jasmainak 
I am in the process of uploading the updated files for the two sample sets, however,
I am getting warnings for the _photo.jpg, _headshape.jpg and all the files contained within the .ds files.
Also I am getting an error for EpochLength in the _meg.json file, I don't think there is a json value for Inf. So how do I encode a continuous EpochLength?

**Comment by guiomar-niso** [comment]
For EpochLength, if Inf doesn't work maybe we could modify it to be 0 for continuous data?

**Comment by jasmainak** [comment]
> I am getting warnings for the _photo.jpg, _headshape.jpg and all the files contained within the .ds files

Can you upload this dataset somewhere (like you shared the link before)? So, I can modify the validator accordingly.

I'm fine with using 0 for continuous data

**Comment by ebock** [comment]
The links I sent previously should work. If not, here they are again
https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory
https://box.bic.mni.mcgill.ca/s/sample_BIDS_omega

**Comment by ebock** [comment]
Also, for the validator, when I have digitized coils but not digitized landmarks, then in the meg.json I have the field DigitizedLandmarks=false, but it complains that in the fid.json I should have LandmarkCoordinates, etc. This should be dependant on whether there are landmarks available. You can see the warnings...

**Comment by jasmainak** [comment]
okay thanks. Sorry I didn't get time to look today. I'll try to fix it tomorrow!

**Comment by jasmainak** [comment]
> I am in the process of uploading the updated files for the two sample sets, however,
> I am getting warnings for the _photo.jpg, _headshape.jpg and all the files contained within the .ds files.

okay, this is fixed now

**Comment by jasmainak** [comment]
> Also, for the validator, when I have digitized coils but not digitized landmarks, then in the meg.json I have the field DigitizedLandmarks=false, but it complains that in the fid.json I should have LandmarkCoordinates, etc. This should be dependant on whether there are landmarks available. You can see the warnings...

Yes, but then shouldn't LandmarkCoordinates be made an optional field?

**Comment by ebock** [comment]
Yes. It should be dependent on whether or not there are DigitizedLandmarks.

**Comment by robertoostenveld** [comment]
since this is a rather large issue with distributed responsibilities, I split it up into #38 and #39.

**Comment by guiomar** [comment]
Both #38 and #39 are solved now, so we can close this issue :)
