### ISSUE TITLE
_fid.json in brainstorm MEG example

### ISSUE THREAD

**Issue by jasmainak** [INCF/BIDS-examples#29]
@dorahermes reported that https://github.com/INCF/BIDS-examples/blob/bep008_meg/brainstorm_sample_auditory/sub-0001/meg/sub-0001_fid.json is not up to date with BEP008 standard ...

**Comment by robertoostenveld** [comment]
hi @dorahermes, could you send a PR to fix it?

**Comment by robertoostenveld** [comment]
This is not the only problem with the brainstorm_sample_auditory. Better to follow them up jointly at ##38
