### ISSUE TITLE
questions regarding iEEG

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#31]
@dorahermes thanks for the example. I have some questions:

Why is sub-01_acq-projected_locinfo.txt not part of the ub-01_acq-projected_loc.json file, e.g. as an info field?

Why is sub-01_acq-projected_loc.tsv not part of the channels.tsv file? (Perhaps because of the next question...)

How is the difference between channels (i.e. entities of the amplifier) and electrodes (metallic contacts to the tissue) described? Think about bipolar channels and referencing: we have this in EEG, but not in MEG.

**Comment by robertoostenveld** [comment]
note that channels~=electrodes is an open issue for EEG on https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit

Perhaps discussing it in relation to iEEG can help clarify it for EEG as well. 

As background: for MEG we decided not to specify sensor location as [x y z], as magnetometer coils are not point-like and gradiometers have an even more explicit spatial extent of multiple cm.

**Comment by choldgraf** [comment]
IMO if we can find a reason to merge two files into one, I am for it. Why don't we add a "Description" field in the `*_loc.json` file, e.g.:

```
{
 "IEEGCoordinateSystem": "Talairach-Tournoux",
 "iEEGCoordinateUnits": "mm",
 "iEEGLocationDescription": "We just randomly chose lol"
}
```

**Comment by dorahermes** [comment]
@robertoostenveld Before we knew about the EEG format we intended the _loc.tsv file to only contain positions of the electrodes and the _channels.tsv file to contain all the channel information, including electrode size, type and material etc. This is just because in iEEG we typically get channel information from the clinical setting, and derive electrode positions from a separate analysis pipeline (such as coregistration between CT/MRI). I would like to make sure that when we get channel information from the clinic, it is all in one file, would this pose a big problem in Fieldtrip?

**Comment by robertoostenveld** [comment]
the conceptual difference between channels and electrodes is important: a channel is a property of the electronics system (an amplifier and a analog-to-digital converter), an electrode is a conductive disk attached to the subject. A single bipolar channel requires two electrodes, a N-channel recording with a common reference requires N+1 electrodes (and often involves N+1+1, as there is also a ground electrode). By off-line re-referencing or filtering you can change the channel properties, but not the electrode properties. By off-line coregistration with anatomical data (MRI/CT) you add extra information about electrodes (i.e. position), but you don't change anything w.r.t. channels. Perhaps in the spec we should mention that some electrode properties are known before-hand  (e.g. size and material), whereas other electrode properties require (geometrical) analysis and data fusion (i.e. position). Some information being known up-front and some information being only known after data fusion also applies to MEG, where we initially express magnetometer/gradiometer positions relative to coils attached to the head, and at a later stage express the coils relative to an MRI, and thereby are able to express magnetometer/electrode positions relative to an MRI or anatomical model.

**Comment by dorahermes** [comment]
I see. In MEG-BIDS the position are in _headshape.extension and the corresponding info in _fid.json. In EEG-BIDS there is currently a _electrodes.tsv, but no corresponding _electrodes.json. For iEEG we could use the _electrodes.tsv (instead of the current _loc.tsv) and _electrodes.json (instead of the current _loc.json). Would that work?

**Comment by robertoostenveld** [comment]
"headshape" contains data that is (optionally) recorded with the MEG system (i.e. with the Polhemus hardware, using the MEG system specific software). Its content is not comparable to the sensors/magnetometers/gradiometers/electrodes. For MEG we decided not to store sensors/magnetometers/gradiometers details in an extra file, since information on it is represented in the manufacturer specific MEG data files. Position, orientation and size/geometry of the MEG coils is more difficult to describe than electrode positions. I think _electrodes.tsv is a good one. What would be represented in _electrodes.json?

**Comment by dorahermes** [comment]
The _electrodes.json file would replace the name of the current _loc.json file. It has the coordinate system, units, corresponding image etc. This is the iEEG equivalent of the MEG _fid.json.

**Comment by StolkArjen** [comment]
This is looking good. A couple of random thoughts, based on https://github.com/INCF/BIDS-examples/blob/bep008_meg/brainstorm_sample_auditory/sub-0001/meg/sub-0001_task-AEF_run-01_meg.json ..

- "AssociatedAnatomicalMRI": should there also be an "AssociatedAnatomicalCT" field in the case one wants to revisit/adjust the electrodes in the (MR-fused) CT?

- "Manufaturer"/"ManufacturerModelName": is this a single entity or could it accommodate multiple manufacturers in string array format? For instance, combined grid and depth electrode cases may contain equipment made by different manufacturers, as in the tutorial case on the FT wiki, which has Integra grid and Ad-Tech depths (http://www.fieldtriptoolbox.org/tutorial/human_ecog). Or should the manufacturer details be added in the comment/3rd column of the tsv file (link: https://github.com/INCF/BIDS-examples/blob/bep008_meg/brainstorm_sample_auditory/sub-0001/meg/sub-0001_task-AEF_run-01_channels.tsv)?
  
- "Manufaturer" -> "Manufa**c**turer" (typo)

- @dorahermes  "I would like to make sure that when we get channel information from the clinic, it is all in one file, would this pose a big problem in Fieldtrip?":
Perhaps the following info helps in addressing the point raised by @robertoostenveld. Fieldtrip stores the electrode and channel positions in the elecpos and chanpos fields of an _"elec"_ structure, which for iEEG is the output from ft_electrodeplacement, but for EEG and MEG the same elec structure could be constructed from, for instance, header, polhemus, and template files. The elecpos field contains the original electrode positions. With exception of possible brain shift compensation, this field is not adjusted. The channel positions in the chanpos field are initially identical to the electrode positions but may be updated to accommodate offline adjustments in channel combinations, i.e. during re-montaging. Where possible, Fieldtrip also uses a tra field in the elec structure for expressing the relationship between elecpos and chanpos. The tra field is a matrix with the weight of each electrode into each channel, which at the iEEG localization stage merely is an identity matrix reflecting one-to-one mappings between electrodes and channels.

**Comment by choldgraf** [comment]
thanks for the points @StolkArjen ! re: manufacturername, I'd be fine if this were a comma-separated string. @dorahermes do you have any opinions on that?

**Comment by robertoostenveld** [comment]
Regarding AssociatedAnatomicalCT (good idea!): I think it should be AssociatedCT since all CT is aantomical (whereas MRI comes in func and anat flavours).

**Comment by choldgraf** [comment]
+1 to `AssociatedCT`

**Comment by dorahermes** [comment]
- @StolkArjen and @choldgraf re: manufacturername, would it work to subdivide into iEEGSurfChannelManufacturer and iEEGDepthChannelManufacturer, and have an optional column for manufacturer in the _electrodes.tsv file for more complicated cases? (we can have this in case of normal grid, mini grid and depth)

- +1 to making the AssociatedImage field more flexible, we can have MRI, CT or photo. BIDS-MEG recently changed the associated mri field to IntendedFor and then specified the "AssociatedMRICoordinateSystem/Units", iEEG could use "AssociatedImageCoordinateSystem/Units" to retain flexibility?

- @robertoostenveld  The channel/electrode differences in the ieeg-BIDS-spec are being updated and the example will follow shortly. This will address several issues :-)

**Comment by dorahermes** [comment]
issues wrt channel/electrode differences are addressed
