### ISSUE TITLE
ds000117 events.tsv files are not correct

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#37]
The bids-validator gives the errors

	1: First column of the events file must be named 'onset' (code: 20 - EVENTS_COLUMN_ONSET)
	2: Second column of the events file must be named 'duration' (code: 21 - EVENTS_COLUMN_DURATION)

```
mac011> head ds000117/sub-01/ses-meg/beh/sub-01_ses-meg_task-facerecognition_events.tsv 
response_time	button_press	stim_file
1.553	3	meg/f123.bmp
1.586	1	meg/f045.bmp
2.139	1	meg/f135.bmp
1.571	1	meg/u021.bmp
0.955	3	meg/f038.bmp
1.485	1	meg/u052.bmp
1.386	3	meg/f081.bmp
1.474	2	meg/f024.bmp
1.054	1	meg/u116.bmp
```

Looking at ftp://ftp.mrc-cbu.cam.ac.uk/personal/rik.henson/wakemandg_hensonrn/ I see that the BIDS version on the FTP and on this repository are not consistent. 

Looking at https://openfmri.org/s3-browser/?prefix=ds000117/ds000117_R0.1.1/uncompressed/ I see that the version over there is yet another one...

**Comment by chrisfilo** [comment]
@jbwexler  could you make sure this repo will include the latest release of ds000117 from openfmri?

**Comment by jbwexler** [comment]
This should be fixed once this is merged: https://github.com/INCF/BIDS-examples/pull/27

**Comment by choldgraf** [comment]
as #27 is merged can this now be closed?

**Comment by jasmainak** [comment]
yep, let's close it
