### ISSUE TITLE
brainstorm_sample_auditory dataset does not pass the bids-validator

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#38]
The bids-validator (using the current meg-validator branch from @jasmainak) returns the following problems

	1: Empty cell in TSV file detected: The proper way of labeling missing values is "n/a". (code: 23 - TSV_EMPTY_CELL)
	2: Not a valid JSON file. (code: 27 - JSON_INVALID)
	3: This file is too small to contain the minimal NIfTI header. (code: 36 - NIFTI_TOO_SMALL)
	4: Participant labels found in this dataset did not match the values in participant_id column found in the participants.tsv file. (code: 49 - PARTICIPANT_ID_MISMATCH)
	5: JSON file is not formatted according the the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
	1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you can ignore this warning. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)

**Comment by ebock** [comment]
the brainstorm_sample_auditory is not a dataset that I have worked on and is not being managed by our group. I have the following two datasets which should be up to date with respect to the meg-validator. They are also the ones that will be uploaded to openneuro.org:
https://box.bic.mni.mcgill.ca/s/sample_BIDS_auditory
https://box.bic.mni.mcgill.ca/s/sample_BIDS_omega

**Comment by robertoostenveld** [comment]
is the brainstorm_sample_auditory not the same data (perhaps still in another format) as sample_BIDS_auditory?

**Comment by ebock** [comment]
Yes. I think it is the same data, but I have prepared the sample_BIDS_auditory with the correct BIDS structure, naming and sidecar files.

**Comment by robertoostenveld** [comment]
👍 

I have downloaded it and will replace the brainstorm sample in the bep06 branch

Verstuurd vanaf mijn iPhone

**Comment by ebock** [comment]
Great! Thanks.

**Comment by robertoostenveld** [comment]
I have passed the json files through https://jsonlint.com to check (all were technically OK) and to format them in a human readable way

**Comment by robertoostenveld** [comment]
sub-emptyroom_task-noise_run-01_meg.json
	"EpochLength": null,

is invalid. The current version of bit.ly/bids_meg specifies

[EpochLength]: Duration of individual epochs in seconds (e.g. 1). If recording was continuous, set value to 0. 

The "0" is a proposal from Guitar, it used to be Inf. But null is definitely not correct.

**Comment by ebock** [comment]
Oh, yes. That's true. I originally tried to encode the Inf, but there is no json code for that. We then decided to use 0 and I updated it, but apparently only on my local copy. What is the best way to update those fields now?

**Comment by robertoostenveld** [comment]
Don’t worry, I’ll update it to “0” on the github copy. You should do the same on the google drive copy.

**Comment by jasmainak** [comment]
@robertoostenveld are you aware that these datasets are now on openfmri: https://openfmri.org/dataset/ds000246/? Do we have potentially redundant copies of the same dataset?

**Comment by robertoostenveld** [comment]
I did not know, I was only aware of the copy on that Elizabeth pointed me to on her box.bic.mni.mcgill.ca.

I see that on openfmri they have been given other names (ds000246 up to ds000248) than what they now have on the BEP06_meg branch in BIDS-examples. That needs to be fixed (on the bep06 branch). I will do that.

However, they are still not valid with respect to the meg branch of the validator and with respect to the draft specification. The only version that I can contribute to is the one on the bep06 branch. How to get the fixes pushed upstream to openfmri and wherever these data might also be hosted?

**Comment by jasmainak** [comment]
I think @jbwexler is in charge of the openfmri datasets. Pushing it to this website is not as trivial as github if I understand correctly but it has the advantage that you can host all your files (including those greater than 100 MB) rather than just the sidecars.

**Comment by robertoostenveld** [comment]
the information on the fiducials is not defined at the run level but at the file level. Hence I think that the two (identical) files

```mac011> ls -al *fid.json
-rw-r--r--  1 roboos  staff  2630 Nov 14 15:09 sub-0001_task-AEF_run-01_fid.json
-rw-r--r--  1 roboos  staff  2630 Nov 14 15:09 sub-0001_task-AEF_run-02_fid.json 
```

should be merged and named sub-0001_fid.json. That would put them at the same level as 

```
-rw-r--r--  1 roboos  staff  13132 Nov 14 14:58 sub-0001_acq-LPA_photo.jpg
-rw-r--r--  1 roboos  staff   4351 Nov 14 14:58 sub-0001_acq-NAS_photo.jpg
-rw-r--r--  1 roboos  staff  13374 Nov 14 14:58 sub-0001_acq-RPA_photo.jpg
-rw-r--r--  1 roboos  staff   9957 Nov 14 14:58 sub-0001_headshape.pos 
```

which also apply to all runs in the MEG session. 

Acquisition settings and channel details can differ from run to run, hence the _channels.tsv and the _meg.json files are to be specified for each run (as they are now).

**Comment by guiomar** [comment]
Ok. It's true, coordsystem.json (previosly fid.json), is session specific so no need to repeat it for each run. I'll merge them.
