### ISSUE TITLE
mne_sample_data dataset does not pass the bids-validator

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#39]
The bids-validator (using the current meg-validator branch from @jasmainak) returns the following problems

	1: First column of the events file must be named 'onset' (code: 20 - EVENTS_COLUMN_ONSET)
	2: Second column of the events file must be named 'duration' (code: 21 - EVENTS_COLUMN_DURATION)
	3: Not a valid JSON file. (code: 27 - JSON_INVALID)
	4: This file is too small to contain the minimal NIfTI header. (code: 36 - NIFTI_TOO_SMALL)
	1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you can ignore this warning. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)

**Comment by robertoostenveld** [comment]
Item 4 makes sense and is not a problem, the raw data files has been truncated to 0 bytes.

The last one (which is confusingly called "1" just like the first one) is something that needs updates in the bids-validator. But there are also some files in the dataset that should not be there.

Items 1-3 are real.

**Comment by robertoostenveld** [comment]
@agramfort mentioned in #issuecomment-315560533 that @jasmainak will have a look at this.

**Comment by jasmainak** [comment]
@robertoostenveld there is an open PR here: https://github.com/INCF/BIDS-examples/pull/34

Also, since I did not see anyone responding to my PR, for I switched to [google drive](https://drive.google.com/drive/folders/0B_sb8NJ9KsLUQ3BMS0dxZW5nSHM?usp=sharing). @jbwexler is in the process of uploading them to OpenNeuro

**Comment by chrisfilo** [comment]
You can use the `--ignoreNiftiHeaders` flag to skip checking headers.

**Comment by jasmainak** [comment]
> You can use the --ignoreNiftiHeaders flag to skip checking headers.

Cool !

**Comment by robertoostenveld** [comment]
Please note that the directory has been renamed to ds000248, see https://github.com/INCF/BIDS-examples/issues/38#issuecomment-344314881

**Comment by guiomar** [comment]
@robertoostenveld @jasmainak can we close this?

**Comment by jasmainak** [comment]
okay for me

**Comment by guiomar** [comment]
Ok, let's close this
