### ISSUE TITLE
examples are not consistent between github and google drive

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/BIDS-examples#40]
The examples on https://drive.google.com/drive/u/0/folders/0B2JWN60ZLkgkMGlUY3B4MXZIZW8
are not consistent with the examples in this github repo.

I see that as a problem, because it is unclear which of the two prevails. Updates to one might also be overwritten by (conflicting) updates in the other.

I propose the policy that the github repo sidecar files (in the master) are the definitive ones, and that the raw data files on the google drive are the definitive ones (obviously, because in the repo they are truncated). The policy would imply that tar files should be re-constructed upon a change to the master branch in the repo. It also implies that for all tar files the corresponding directory should be in the repo.

**Comment by robertoostenveld** [comment]
more specifically: 
- hcp_bids_example.tar is present on google drive and missing in the repository
- pet_phno.tar is present on google drive and missing in the repository

**Comment by chrisfilo** [comment]
Closed via #42
