### ISSUE TITLE
Better coverage of all variable types

### ISSUE THREAD

**Issue by tyarkoni** [INCF/BIDS-examples#46]
Right now there are several variable types in the BIDS spec that don't occur in any of the example datasets:

* _stim.tsv.gz
* _confounds.tsv.gz
* _beh.json

Also, the existing `*_physio.tsv.gz` files (which only occur in one dataset) are empty. I get the rationale for not including the full nifti images, but for testing purposes, we should probably include the content of all TSVs.

What would be ideal for my purposes (i.e., for testing pybids properly) would be to have a single dataset that has *all* types of variables represented (i.e., events, physio, stim, confounds, beh, scans, sessions, and participants). The data contained could be nonsensical (though it should be valid). @effigies, if I'm holding you up, can you put something like this together?

**Comment by effigies** [comment]
From grepping through the ///openfmri/ namespace in Datalad, I've found these files in:

* `_stim.tsv[.gz]` - ds238
* `_physio.tsv[.gz]` - ds030, ds113c, ds113d, ds210
* `_beh.json` -  ds030, ds113d, ds117, ds201, ds217

Do we want to keep the data valid for actual OpenFMRI datasets? Or would copying and truncating/padding a `_confounds` from some other run to the right length be okay?

If we want to keep things true to their sources, we could make a `synthetic/` dataset just designed to have all of these, stealing `_stim` from here, `_physio` from there, etc. In this case, what would be good? I'd think 5-subject, 2-session, 2-task should exercise most code reasonably. Anything else you'd want?

**Comment by effigies** [comment]
Do you ever read NIFTIs to get TR or number of volumes? Would it be useful for files in a synthetic dataset to have headers but be truncated before the data array? (Nibabel at least doesn't read data until called.)

**Comment by tyarkoni** [comment]
I don't really care if the data are valid in the sense of being usable for real analyses. I like the idea of a `/synthetic` dataset that steals from various places. Though it's also fine with me if the synthetic dataset only lives in pybids tests, and not in this repo, in which case we don't need to worry about confusing people.

5-subject, 2-session, 2-task sounds good. Maybe also 2 runs per session, to make sure we can test handling of multiple instances at every level.

I do read niftis if they exist, and the absence of the image contents in the test datasets is indeed a problem for testing. That said, to work around this, I currently allow a `scan_length` argument to be specified explicitly in places that need it (though the package still tries to check the niftis first). If you could have real headers retained, that would be awesome.

**Comment by effigies** [comment]
What are you hoping to find in `_beh.json`. There's not much to go by in the spec.

**Comment by effigies** [comment]
Similarly, do you have any example `_stim.tsv` files? Is it basically like `physio` but with unconstrained column names?

**Comment by tyarkoni** [comment]
Re: `_beh.json`, the spec says they're in the same format as metadata. And only subject and task are mandatory (where I believe task is not the name of an fMRI task, but of a behavioral one). So in practice this will be treated just like data in `participants.tsv` (other than the obvious format differences). If you just dump, say, 2 _beh files for each subject, with different task names, and a few key: value pairs inside each one (e.g., for 'RT', 'accuracy', etc.), that should do nicely.

`_stim.tsv` is identical in all respects to `physio`, I believe. The naming convention is just to distinguish whether the files contain presented information, or recorded information. It's not essential that we have both, I guess, since the core code I use is the same for both of them. But it wouldn't hurt--even if you just copy some physio files over and give them different column names.

**Comment by effigies** [comment]
Okay. Does the spec need to be updated to permit `_beh.json` files for MRI experiments? So far they only show up in **8.7 Behavioral experiments (with no MRI)**.

**Comment by tyarkoni** [comment]
I agree that the wording could be refined, but I'm pretty sure the intended meaning is that it's for behavioral data that one might want to model in relation to (f)MRI data, but that weren't actually conducted in the scanner (or even during a scanning session). As I read it, one could in principle enter that kind of data either in `_beh.json` files, or in `participants.tsv`. To be honest I don't really know what the point of having `_beh.json` is, except maybe as a way of organizing data more flexibly.

Actually, now that I'm looking at the spec again, it seems that it also allows for data in `participants.tsv` to be broken up into individual files in a `phenotypes` folder. So that's something I'll need to add support for. And makes it even less clear why one would need a `_beh.json` convention. But I guess we're stuck with it now.

In any event, I don't think we want to allow in-scanner tasks to be coded in `_beh.json` files, since these will always be tied to a particular run or session--so they should probably be included at  Maybe @chrisfilo can clarify.

**Comment by effigies** [comment]
Okay, just to be clear, a `_beh.json` would be placed and contain something like the following?

* `sub-01/ses-01/func/sub-01_ses-01_task-nback_beh.json`
```JSON
{
    "TaskName": "nback",
    "TaskDescription": "N-Back Working Memory Task",
    "MeanRT": 0.6,
    "accuracy": 0.72
}
```

**Comment by tyarkoni** [comment]
I'm 92.6% sure that's right (again, @chrisfilo can chime in if I'm wrong).

**Comment by tyarkoni** [comment]
Oh, except that it seems they go in their own folder. So it would be more like:

```
sub-01/ses-01/beh/sub-01_ses-01_task-nback_beh.json
```

**Comment by effigies** [comment]
Okay. I'll wait on @chrisfilo's authoritative answer to update #48. If you want to work from that branch and make sure that what's done looks reasonable, it should have everything else.

**Comment by tyarkoni** [comment]
Ugh, now I'm really confused: the spec explicitly says that the `beh` folder can contain data from either in-scan or behavioral tasks. And it can apparently also contain files any of the other formats (events, physio, etc.). This is going to make reading all of this a real pain in the ass. Ugh.

**Comment by tyarkoni** [comment]
Awesome, thanks!

Just to update you, I've spent the last 3 days completely overhauling the analysis module. But I'm very confident this will be the last major revision for a long time. Everything works very nicely now and I'm just un-fucking everything step-by-step before getting back to the thing that prompted this all (the contrast management). Took longer than I thought, but should be done by Monday.

**Comment by chrisfilo** [comment]
Yes they go into `beh`. Just reread the paragraph and it does not mention including data from MR tasks (although one could include events and physio data obtained outside of the scanner). Does this clarify things?
