### ISSUE TITLE
Some CI setup which would run bids-validator on the datasets to guarantee they are all ok

### ISSUE THREAD

**Issue by yarikoptic** [INCF/BIDS-examples#5]
ATM I don't know if we could use this as "BIDS-compliant"  ones ;)

**Comment by chrisfilo** [comment]
Geez like this - https://github.com/INCF/bids-validator/blob/master/tests/bids.spec.js?

The validator is tested agains this set of example datasets in CircleCI: https://github.com/INCF/bids-validator/blob/master/circle.yml#L10

**Comment by yarikoptic** [comment]
yes, it is the validator tested against this datasets, not these datasets (and possible new PRs if new stuff comes in) tested to be correct per se.
