### ISSUE TITLE
Labeling datasets by data type or using subfolders

### ISSUE THREAD

**Issue by choldgraf** [INCF/BIDS-examples#52]
As this repository now has a `master` branch with fMRI datasets, and `bep006_XXX` branches with EEG, MEG, and iEEG data, would it be worth re-organizing files into subfolders or via naming convention so that it's easier for users to determine which file is relevant?  It seems like there are a couple options:

1. Improve the [wiki pages that link to datasets](https://github.com/INCF/BIDS-examples/wiki/MRI-datasets). This could be updated with new links / new sections for MEG/iEEG
2. Organize into sub-folders (`fMRI, EEG, MEG, iEEG, mixed`)
3. Have dataset type information in the folder name (e.g., `ds_fmri_003`, `ds_fmri_eeg_004`)

Curious what people think about this.

**Comment by chrisfilo** [comment]
I think improving the wiki is a no-brainer, but adding a new folder level
will require changes in validator automated tests.

**Comment by choldgraf** [comment]
that's a good point - I'm gonna change the title of this issue to reflect updating the wiki

**Comment by choldgraf** [comment]
scratch that, I'll close this issue and open one about updating the wiki :-)
