### ISSUE TITLE
Update the wiki to list new datasets

### ISSUE THREAD

**Issue by choldgraf** [INCF/BIDS-examples#53]
Right now the wiki is the main place to make sense of this repository. 

https://github.com/INCF/BIDS-examples/wiki

As it is rather complex (with multiple branches for many specifications) there is some low-hanging fruit to improve explanations on the wiki site. At a minimum we could:

1. Add links to each branch that contains the MEG/EEG/iEEG specification
2. Add updated paths for new datasets that have been added (including EEG/MEG/iEEG)

**Comment by guiomar** [comment]
Thanks! How can we update MEG examples wiki?
