### ISSUE TITLE
Non BIDS files in MEG example ds000248

### ISSUE THREAD

**Issue by chrisfilo** [INCF/BIDS-examples#56]
![image](https://user-images.githubusercontent.com/238759/36749904-fe9e4134-1bb0-11e8-9954-6c4b08b02d7f.png)
https://github.com/INCF/BIDS-examples/tree/bep008_meg/ds000248/sub-01/meg

@robertoostenveld

**Comment by jasmainak** [comment]
I think the problem is that you need these files to Maxwell filtering. The BIDS specification does not disallow files which do not conform to the format, does it?

**Comment by chrisfilo** [comment]
It doesn't, but the validator will raise a warning if they are not in `.bidsignore`. If those files are "needed" and part of an example why aren't they covered by the spec?

**Comment by jasmainak** [comment]
Hmm ... the specification used to mention it I think. I am not sure why it's not there any more.

But yeah, the *.py files can go and perhaps the `audvis.ave` could go to `derivatives/` folder.

**Comment by jasmainak** [comment]
The cross talk and fine calibration files are required to do Maxwell filtering and they are specific to the site of recording. One could argue that the files processed using maxwell filter are "derivatives". Therefore, if you really wanted to ship the files before any processing, you they would have to be accompanied by these files.

**Comment by guiomar** [comment]
Maxfilter calibration files should go into the derivatives (the proc-sss meg data and corresponding files too). We didn't specified how these Maxfilter calibration files should be named yet. I guess this will be solved when we work on the derivatives. For the moment, yes I guess that they will depend on the site of recording and the safest thing is to keep them there.

**Comment by guiomar** [comment]
Is this solved now?

**Comment by chrisfilo** [comment]
Still seems to be there https://github.com/INCF/BIDS-examples/tree/bep008_meg/ds000248/sub-01/meg

**Comment by guiomar** [comment]
@jasmainak fixed?

**Comment by jasmainak** [comment]
yes
