### ISSUE TITLE
BIDS for preprocessed data and statistics

### ISSUE THREAD

**Issue by TheChymera** [INCF/BIDS-examples#7]
Is there any initiative to extend BIDS to preprocessed data and statistical summaries? The BIDS structure seems to work nicely for the preprocessed data and the first-level (per-session&subject&scan) statistics in [my pipelines](https://github.com/TheChymera/SAMRI). Also, per-scan-type, per-subject, and per-session second-level statistics seem like common enough use cases. So I, at least, am also using a BIDS-flavoured structure for that.

Are there already drafts on this? If not, what's a good place to discuss writing some?

**Comment by chrisfilo** [comment]
Yes there is! Here's a draft of [BIDS Derivatives](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit).

For results of statistical inferences please have a look at [NIDM Results](http://nidm.nidash.org/specs/nidm-results_130.html).

BTW For BIDS related questions I recommend using the [bids-discussion mailing list](https://groups.google.com/forum/#!forum/bids-discussion).
