### ISSUE TITLE
Rename MEG dataset names

### ISSUE THREAD

**Issue by guiomar** [INCF/BIDS-examples#71]
Hi!

Since Open Neuro doesn't keep track of the dataset numbers, I think it will be good to rename them:

- ds000246 --> Brainstorm_Auditory_dataset (https://openneuro.org/datasets/ds001325)
- ds000247 --> OMEGA_RestingState_sample (https://openneuro.org/datasets/ds001329)
- ds000248 --> MNE_sample (https://openneuro.org/datasets/ds001328)
- ds000117 --> ? (https://openneuro.org/datasets/ds001326)

@chrisfilo @jasmainak @rikhenson

**Comment by jasmainak** [comment]
no opinion but you will also have to update the validator

**Comment by chrisfilo** [comment]
We are planning to fix the open neuro accession numbers for historical datasets to match the openfmri ones this week.

**Comment by RikHenson** [comment]
ds000117 -> SPM_Multimodal_Group_Example ?

---------------------------------------------------------------
Prof Richard Henson
Deputy Director
MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  rik.henson@mrc-cbu.cam.ac.uk<mailto:rik.henson@mrc-cbu.cam.ac.uk>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
TEL     +44 (0)1223 355 294 x501
FAX     +44 (0)1223 359 062
MOB     +44 (0)794 1377 345
---------------------------------------------------------------

**Comment by chrisfilo** [comment]
Dataset numbers in OpenNeuro have been updated to match the openfmri ones.

**Comment by jasmainak** [comment]
Great, thanks

**Comment by guiomar** [comment]
Thanks!! @jasmainak @chrisfilo 

The reviewer of the manuscript just clicked after the change, so the links didn't work. It's good that we have the chance to update them now :)

This one is missing though:
ds000247 --> OMEGA_RestingState_sample (https://openneuro.org/datasets/ds001329)

**Comment by guiomar** [comment]
@chrisfilo could it be fixed soon so we can resubmit today?

**Comment by chrisfilo** [comment]
@rwblair could you look into renaming that one dataset? Thanks in advance.

**Comment by rwblair** [comment]
@guiomar My apologies about that, the dataset has been updated at this time:
https://openneuro.org/datasets/ds000247

If you see any issues with it please let us know.

**Comment by chrisfilo** [comment]
Thanks Ross!

**Comment by guiomar** [comment]
Thank you so much @rwblair!! :)
