### ISSUE TITLE
TSV files in ds101

### ISSUE THREAD

**Issue by gllmflndn** [INCF/BIDS-examples#8]
The end of each line (after the header) of the TSV files in ds101, eg:
https://github.com/INCF/BIDS-examples/blob/master/ds101/sub-01/func/sub-01_task-Simontask_run-01_events.tsv
is '\t \n': shouldn't it be 'n/a' instead of a space?

**Comment by chrisfilo** [comment]
@suyashdb could you look into this?

**Comment by gllmflndn** [comment]
This has been fixed in https://github.com/INCF/BIDS-examples/commit/df660daa33500c1970389e386d8dc50f19afda99
Thanks
